apiVersion: v1
kind: Secret
metadata:
  name: cortex-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cortex.labels" . | nindent 4 }}
type: Opaque
stringData:
  sovereignAdminPassword: {{ .Values.secrets.sovereignAdminPassword | quote }}
  cortexApiKey: {{ .Values.secrets.cortexApiKey | quote }}
  beaconBraveApiKey: {{ .Values.secrets.beaconBraveApiKey | quote }}
  beaconSearxngUrl: {{ .Values.secrets.beaconSearxngUrl | quote }}
